Lab 1
BurgheRlyeh/Operating-Systems-Labs pull request #1
Opened 2023-10-29 19:12 UTC by BurgheRlyeh

Task 19 (Reminder)

2023-11-02 17:30 UTC, DariaWelt requested changes
Ваш демон не собирается

```
- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/daria/Downloads/Operating-Systems-Labs-lab1/lab1/temp
[ 33%] Building CXX object CMakeFiles/reminder.dir/main.cpp.o
[ 66%] Building CXX object CMakeFiles/reminder.dir/Reminder.cpp.o
/home/daria/Downloads/Operating-Systems-Labs-lab1/lab1/Reminder.cpp: In member function ‘void Reminder::init(std::string)’:
/home/daria/Downloads/Operating-Systems-Labs-lab1/lab1/Reminder.cpp:24:5: error: ‘getcwd’ was not declared in this scope; did you mean ‘getw’?
   24 |     getcwd(buf, sizeof(buf));
      |     ^~~~~~
      |     getw
/home/daria/Downloads/Operating-Systems-Labs-lab1/lab1/Reminder.cpp: In member function ‘void Reminder::toDaemon()’:
/home/daria/Downloads/Operating-Systems-Labs-lab1/lab1/Reminder.cpp:62:16: error: ‘fork’ was not declared in this scope
   62 |     pid_t pid{ fork() };
      |                ^~~~
/home/daria/Downloads/Operating-Systems-Labs-lab1/lab1/Reminder.cpp:77:9: error: ‘setsid’ was not declared in this scope
   77 |     if (setsid() < 0) {
      |         ^~~~~~
/home/daria/Downloads/Operating-Systems-Labs-lab1/lab1/Reminder.cpp:83:9: error: ‘chdir’ was not declared in this scope
   83 |     if (chdir("/") < 0) {
      |
```

2023-11-02 17:30 UTC, DariaWelt commented on lab1/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
вам действительно нужен 20 стандарт?
По условию задания мы пользуемся стандартами до 14, но так как в filesystems много полезных штук для лаб, разрешен был и 17 стандарт. Нужно переделать работу под 17 стандарт максимум.

2023-11-06 16:09 UTC, BurgheRlyeh commented
Изменил версию на C++14

2023-11-14 20:15 UTC, DariaWelt commented on lab1/Reminder.cpp
> +void Reminder::init(std::string configFile) {
Передаете строку по значению, а не по ссылке

2023-11-14 20:55 UTC, DariaWelt requested changes
Демон работает.
Уберите вывод лога в консоль.

2023-11-14 20:55 UTC, DariaWelt commented on lab1/Reminder.cpp
> +    openlog("Reminder", LOG_NDELAY | LOG_PID | LOG_PERROR, LOG_USER);
Уберите LOG_PERROR, логи дублируются в вызывающий терминал

2023-11-16 18:30 UTC, DariaWelt approved these changes
Работа зачтена

2023-11-16 18:31 UTC, merged